# Generated by Django 3.2.8 on 2021-10-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('avgspeed', models.FloatField(blank=True, null=True)),
                ('Temperature', models.FloatField(blank=True, null=True)),
                ('fuellevel', models.FloatField(blank=True, null=True)),
                ('enginestats', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
