# Generated by Django 3.2.8 on 2021-10-31 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='image1',
            field=models.ImageField(default='', upload_to='vehicleimg/image1'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='image2',
            field=models.ImageField(default='', upload_to='vehicleimg/image2'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='Temperature',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=100000, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='avgspeed',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=100000, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='enginestats',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=100000, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='fuellevel',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=100000, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='speed',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=100000, null=True),
        ),
    ]
