# Generated by Django 3.2.8 on 2021-10-31 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vapp', '0003_auto_20211031_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='Temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='avgspeed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='enginestats',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='fuellevel',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='speed',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
