# Generated by Django 3.2.8 on 2021-10-31 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vapp', '0007_remove_vehicle_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='title',
            new_name='vehiclename',
        ),
    ]
